### PR TITLE
Add version to define-obsolete-function-alias invocation

### PR DESCRIPTION
**Pull request by kekeimiku**
Emacs 28 requires this argument.
https://emba.gnu.org/emacs/emacs/-/commit/32c6732d16385f242b1109517f25e9aefd6caa5c

### CODE REVIEW

**Comment by yashi** [comment]
It looks good but "1.0" is not true.
```diff
diff --git a/benchmark-init-modes.el b/benchmark-init-modes.el
index 1a5f8c5..eb87e10 100644
--- a/benchmark-init-modes.el
+++ b/benchmark-init-modes.el
@@ -209,7 +209,7 @@
 ;; Obsolete functions
 
 (define-obsolete-function-alias 'benchmark-init/show-durations
-  'benchmark-init/show-durations-tabulated)
+  'benchmark-init/show-durations-tabulated "2014-04-05")
 
 (provide 'benchmark-init-modes)
 ;;; benchmark-init-modes.el ends here
diff --git a/benchmark-init.el b/benchmark-init.el
index 90a69df..4a6aca1 100644
--- a/benchmark-init.el
+++ b/benchmark-init.el
@@ -189,7 +189,7 @@ Slots:
 ;; Obsolete functions
 
 (define-obsolete-function-alias 'benchmark-init/install
-  'benchmark-init/activate)
+  'benchmark-init/activate "2014-03-17")
 
 (provide 'benchmark-init)
 ;;; benchmark-init.el ends here
```

**Comment by Makima0** [comment]
> It looks good but "1.0" is not true. Here are the dates they were obsoleted.
> 
> ```diff
> diff --git a/benchmark-init-modes.el b/benchmark-init-modes.el
> index 1a5f8c5..eb87e10 100644
> --- a/benchmark-init-modes.el
> +++ b/benchmark-init-modes.el
> @@ -209,7 +209,7 @@
>  ;; Obsolete functions
>  
>  (define-obsolete-function-alias 'benchmark-init/show-durations
> -  'benchmark-init/show-durations-tabulated)
> +  'benchmark-init/show-durations-tabulated "2014-04-05")
>  
>  (provide 'benchmark-init-modes)
>  ;;; benchmark-init-modes.el ends here
> diff --git a/benchmark-init.el b/benchmark-init.el
> index 90a69df..4a6aca1 100644
> --- a/benchmark-init.el
> +++ b/benchmark-init.el
> @@ -189,7 +189,7 @@ Slots:
>  ;; Obsolete functions
>  
>  (define-obsolete-function-alias 'benchmark-init/install
> -  'benchmark-init/activate)
> +  'benchmark-init/activate "2014-03-17")
>  
>  (provide 'benchmark-init)
>  ;;; benchmark-init.el ends here
> ```

Thank you for the correction.

**Comment by kaushalmodi** [comment]
@dholm A gentle nudge to merge this PR please.

**Comment by manuel-uberti** [comment]
@dholm kindly asking thing @kaushalmodi asked. :)

**Comment by weidtn** [comment]
@purcell maybe you can merge this?

**Comment by purcell** [comment]
I don't have commit rights, sorry. But fwiw, this is an uncontroversial and safe change from my perspective.

**Comment by wbolster** [comment]
@dholm is there any others can help you click the merge button? 🙃   (you click it, or invite contributors to this repo, etc.)

**Comment by aladine** [comment]
I drop him an email at dholmster@gmail.com. Hopefully, he will go online, merge this pull request and save the world.

**Comment by dholm** [comment]
Thank you very much for the contribution.  Sorry for not reacting sooner.

**Pull request merged**
